Repository afterWe/Run_Base_front-end, pull requests merged in 2023-08, with the labels that each got.

#2 ADD: Login 레이아웃 구성
  src/pages/Login/Login.style.ts
  src/pages/Login/Login.tsx
Labels: 작업완료

#4 ADD: 배송지주소 레이아웃
  src/Router.tsx
  src/layout/component/AddressEdit.style.ts
  src/layout/component/AddressEdit.tsx
Labels: 작업완료

#8 ADD: 배송지주소 레이아웃
  src/layout/component/AddressList.style.ts
  src/layout/component/AddressList.tsx
Labels: 작업완료

#6 [ADD] appLayout 구조 추가
  public/images/runbase_logo.png
  public/images/runbase_logo1.png
  public/images/runbase_logo2.png
  public/images/runbase_logo3.png
  src/layout/component/Footer.tsx
  src/layout/component/Header.tsx
  src/layout/component/style/Footer.style.ts
  src/layout/component/style/Header.style.ts
Labels: 작업중

#11 [ADD] <결제 완료> 페이지 레이아웃 구현 중
  public/images/paid/muyaho.jpg
  src/Router.tsx
  src/Styles/theme.ts
  src/components/Paid/PaidButton/PaidButtonComponent.style.ts
  src/components/Paid/PaidButton/PaidButtonComponent.tsx
  src/components/Paid/PaidTitle/PaidTitleComponent.tsx
  src/data/OrderDetail.json
  src/pages/Paid/Paid.style.ts
  src/pages/Paid/Paid.tsx
  src/pages/Payment/Payment.tsx
Labels: 작업완료

#13 [MODIFY] <로그인> 레이아웃 수정
  src/pages/Login/Login.style.ts
  src/pages/Login/Login.tsx
Labels: 작업완료

#17 MODIFY : 헤더 스타일 변경
  src/layout/component/Header.tsx
  src/layout/component/style/Footer.style.ts
  src/layout/component/style/Header.style.ts
Labels: 작업완료

#14 [MODIFY] <배송지수정> 레이아웃 수정사항 반영
  src/Router.tsx
  src/components/AddressEdit.style.ts
  src/components/AddressEdit.tsx
  src/layout/component/AddressEdit.style.ts
  src/layout/component/AddressEdit.tsx
Labels: 이거좀봐줘

#7 [ADD] <마이페이지> 레이아웃 구현
  public/data/payment.json
  src/components/MyPage/PaymentDetail.style.ts
  src/components/MyPage/PaymentDetail.tsx
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPage.tsx
Labels: 작업중

#12 [ADD] <결제> 페이지 레이아웃 구현 중
  src/pages/Payment/Payment.style.ts
  src/pages/Payment/Payment.tsx
Labels: 작업중

#10 [ADD] <상품 상세> 페이지 레이아웃 구현 중
  public/images/nike.jpg
  src/components/Review.tsx
  src/pages/ProductDetail/ProductDetail.tsx
Labels: 작업중

#20 [MODIFY] <회원가입> 페이지 피드백 적용 완료
  src/pages/SignIn/SignIn.style.ts
  src/pages/SignIn/SignIn.tsx
Labels: 피드백원츄, 작업완료

#30 [ADD] modal 컴포넌트 추가
  src/components/Modal/Modal.style.ts
  src/components/Modal/Modal.tsx
  src/types/components.ts
Labels: 이거좀봐줘, 작업완료

#19 [ MODIFY] <마이페이지> 레이아웃 구현중
  public/data/payment.json
  src/components/Address/AddressList.style.ts
  src/components/MyPage/ChangePw.style.ts
  src/components/MyPage/ChangePw.tsx
  src/components/MyPage/PaymentDetail.style.ts
  src/components/MyPage/PaymentDetail.tsx
  src/components/MyPage/PersonalInfo.style.ts
  src/components/MyPage/PersonalInfo.tsx
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPage.tsx
Labels: 피드백원츄, 작업중

#21 [MODIFY] <결제 완료> 페이지 레이아웃 수정 중
  src/Router.tsx
  src/pages/Payment/Payment.style.ts
  src/pages/Payment/Payment.tsx
Labels: 작업완료

#23 [MODIFY] <로그인> 수정사항 반영
  src/pages/Login/Login.style.ts
  src/pages/Login/Login.tsx
Labels: 작업완료

#24 [MODIFY] <장바구니> 레이아웃 수정
  public/data/cartData.json
  src/pages/Cart/Cart.style.ts
  src/pages/Cart/Cart.tsx
Labels: 피드백원츄, 작업완료

#27 [MODIFY] <배송지추가(수정)> 레이아웃 수정사항 반영
  src/components/Address/AddressEdit.style.ts
  src/components/Address/AddressEdit.tsx
Labels: 피드백원츄

#29 [MODIFY] <회원가입> 페이지 피드백 적용 완료
  src/pages/SignIn/SignIn.style.ts
  src/pages/SignIn/SignIn.tsx
Labels: 이거좀봐줘

#32 [MODIFY] 회원가입 레이아웃 완성
  src/pages/SignIn/SignIn.tsx
Labels: 작업완료

#22 [MODIFY] <결제완료> 페이지 레이아웃 피드백 적용 완료
  public/data/orderDetail.json
  public/data/orderInfo.json
  public/images/paid/force.png
  public/images/paid/force1.png
  public/images/paid/lee.png
  public/images/paid/martin.webp
  public/images/paid/muyaho.jpg
  public/images/paid/travis.webp
  src/components/Paid/OrderDetailComponent.style.ts
  src/components/Paid/OrderDetailComponent.tsx
  src/components/Paid/OrderDetailProps.tsx
  src/components/Paid/OrderInfoComponent.style.ts
  src/components/Paid/OrderInfoComponent.tsx
  src/components/Paid/OrderInfoProps.tsx
  src/data/OrderDetail.json
  src/pages/Paid/Paid.style.ts
  src/pages/Paid/Paid.tsx
  src/types/components.ts
Labels: 피드백원츄, 작업완료

#33 [ADD] <결제> 레이아웃 구현 완료
  public/data/paymentInformation.json
  public/data/paymentOrderList.json
  public/images/payment/airforce.webp
  public/images/payment/pmo.webp
  public/images/payment/psg.webp
  public/images/payment/retro low.webp
  public/images/payment/travis.png
  src/pages/Payment/Payment.style.ts
  src/pages/Payment/Payment.tsx
  src/types/components.ts
Labels: 피드백원츄, 작업완료

#35 [ADD] <마이페이지> 레이아웃 구현
  src/components/MyPage/ChangePw.tsx
  src/components/MyPage/PersonalInfo.style.ts
  src/components/MyPage/PersonalInfo.tsx
Labels: 피드백원츄, 작업중

#34 [ADD] <상품 상세> 페이지 레이아웃
  src/components/Review.tsx
  src/pages/ProductDetail/ProductDetail.style.ts
  src/pages/ProductDetail/ProductDetail.tsx
  src/types/components.ts
Labels: 피드백원츄

#36 [MODIFY] <결제> 레이아웃 피드백 적용 완료
  src/Styles/theme.ts
  src/pages/Payment/Payment.style.ts
  src/pages/Payment/Payment.tsx
Labels: 작업완료

#40 [ADD] <상품 목록> 페이지 레이아웃 _ * 필터링 부분
  src/pages/ProductList/ProductList.style.ts
  src/pages/ProductList/ProductList.tsx
  src/types/components.ts
Labels: 피드백원츄, 작업완료

#41 [MODIFY] <장바구니> 수정사항반영
  src/pages/Cart/Cart.style.ts
  src/pages/Cart/Cart.tsx
Labels: 작업완료

#42 [MODIFY] <배송지수정> 수정사항반영
  src/Router.tsx
  src/components/Address/AddressEdit.style.ts
  src/components/Address/AddressEdit.tsx
  src/types/components.ts
Labels: 작업완료

#44 [ADD] <메인페이지> 레이아웃 구현 중
  public/data/newProductList.json
  public/images/main_banner.jpg
  src/components/ProductCard.tsx
  src/components/ProductCard/ProductCard.style.ts
  src/components/ProductCard/ProductCard.tsx
  src/pages/Main/Main.style.ts
  src/pages/Main/Main.tsx
  src/types/components.ts
Labels: 피드백원츄

#39 [MODIFY] <마이페이지> 레이아웃 피드백 반영중
  public/data/payment.json
  src/components/MyPage/ChangePw.style.ts
  src/components/MyPage/ChangePw.tsx
  src/components/MyPage/PaymentDetail.style.ts
  src/components/MyPage/PaymentDetail.tsx
  src/components/MyPage/PersonalInfo.style.ts
  src/components/MyPage/PersonalInfo.tsx
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/Payment/Payment.tsx
  src/types/components.ts
Labels: 피드백원츄, 작업중

#47 [MODIFY] <상품 목록>페이지 레이아웃 _ *필터 박스 _ 피드백 적용 완료
  src/pages/Main/Main.tsx
  src/pages/ProductList/ProductList.style.ts
  src/pages/ProductList/ProductList.tsx
Labels: 작업완료

#43 [ADD] <배송지목록> 배송지수정 모달 추가
  src/components/Address/AddressList.style.ts
  src/components/Address/AddressList.tsx
  src/types/components.ts
Labels: 작업완료

#50 [MODIFY] <결제> 레이아웃 _ AddressList props 추가!
  src/pages/Payment/Payment.tsx
Labels: 작업완료

#28 [ADD] <헤더> 버튼클릭시 이동구현
  src/layout/component/Header.tsx
Labels: 작업중

#55 [MODIFY]<결제> 레이아웃 _ props 추가
  src/pages/Payment/Payment.tsx
Labels: 작업완료

#45 [ADD] <상품리스트> 상품카드 레이아웃 구현
  src/pages/ProductList/ProductList.style.ts
  src/pages/ProductList/ProductList.tsx
Labels: 피드백원츄, 컨플릭트해결하셈, 작업완료

#56 [ADD] <결제완료> 레이아웃 구현 _ 배송중 상태 props 추가
  public/data/orderInfo.json
  src/components/Paid/OrderInfoComponent.tsx
  src/pages/Payment/Payment.tsx
  src/types/components.ts
Labels: 작업완료

#58 [ADD] <결제 완료> 레이아웃 _ 배송중 상태 props 추가
  src/components/MyPage/PaymentDetail.tsx
  src/pages/Paid/Paid.tsx
  src/pages/Payment/Payment.tsx
  src/types/components.ts
Labels: 작업완료

#62 [FIX] 마이페이지 레이아웃
  public/images/arrow-double.png
  public/images/arrow.png
  src/components/Modal/Modal.style.ts
  src/components/Modal/Modal.tsx
  src/components/MyPage/Pagination.tsx
  src/components/MyPage/PaymentDetail.tsx
  src/types/components.ts
Labels: 작업완료
